const greetings = {
  morning: [
    "Good morning, Mavericks! Time to crush it like a boss! 💥",
    "Wake up, wake up! The world needs your magic today! ✨",
    "Rise and shine, Mavericks! Coffee in one hand, confidence in the other! ☕😎",
    "Top of the morning to the Mavericks! Let's make today legendary! 🏆",
    "Morning, Mavericks! Ready to slay the day? 🔥",
    "Sun's up, Mavericks! So are your dreams—go chase 'em! 🌞",
    "Good morning! Don't hit snooze on greatness! ⏰",
    "Hey Mavericks, did you bring your A-game today? Let's see it! 🎯",
    "Morning MVPs! Time to turn ideas into action! 🚀",
    "Up and at 'em, Mavericks! Today's challenges are just fun puzzles! 🧩",
    "Shoutout to the Mavericks waking up already winning! 🏅",
    "Sun's out, fun's out! Let's make this morning epic! 🌞🎉",
    "Mornings are for Mavericks who hustle before the world wakes! 💪",
    "Good morning, legends! Time to write your success story today! 📖",
    "Wakey wakey, eggs and victory! 🥚🏆",
    "Morning Mavericks! Got your superhero cape on? Let's fly! 🦸‍♂️🦸‍♀️",
    "New day, new goals, same fierce Mavericks! ⚔️",
    "Morning vibes for Mavericks who mean business! 💼",
    "Rise like a Maverick phoenix from the coffee ashes! ☕🔥",
    "Hey Mavericks, time to shake the world awake! 🌍✨",
    "Sun's shining, Mavericks grinding! Let's go! 🌅💥",
    "Good morning! Let's make this day so good, yesterday gets jealous! 😎",
    "Mavericks, ready to conquer before breakfast? Let's do it! 🥐🚀",
    "Happy morning to the coolest Mavericks in town! 😎👊",
    "Rise, Mavericks! It's grind o'clock! ⏰💪",
    "Morning fuel: courage, coffee, and pure Maverick energy! ⚡☕",
    "Up early? That's some boss-level ambition! 🧠👑",
    "Good morning! Make those dreams chase *you* today! 🏃‍♂️💭",
    "Sunrise isn't just light—it's your green signal! 💚🌄",
    "Crack of dawn? More like spark of domination! 🔥",
    "Be louder than your alarm clock, Mavericks! ⏰🎤",
    "The early bird catches... global impact. 🌍✨",
    "Mavericks rise while others sleep. That's how legends are made. 💼😴",
    "New day, new fire, same Mavericks! 🔥💯",
    "Ready to caffeinate and dominate? ☕💥",
    "Set goals so loud they wake your neighbours! 📣💡",
    "Kick today so hard it apologizes tomorrow. 👢📅",
    "Sunrise squad reporting for duty! 🌄🫡",
    "First task of the day: Be awesome. ✔️",
    "Good morning! Time to hustle like it's the finals! 🏁📈",
    "Today is the playground, Mavericks are the champions! 🛝🏆",
    "Be the storm that breaks morning silence! ⛈️💪",
    "Your energy this morning? 1000% Maverick-grade! ⚡",
    "Shine so bright today the sun asks for your shades. 😎🌞",
    "The grind doesn’t sleep — but you woke up before it! 🧠⏰",
    "Turn 'meh' mornings into mega missions! 💼💣",
    "Alarm rang. You answered like a warrior. 🗡️⏰",
    "Don’t wait for opportunity. Brew it. ☕🔨",
    "A new day to outdo your past self. Start now. 🏋️‍♂️📊",
    "Wake up. Show up. Glow up. 🚿🔥",
    "Mornings are short — make them loud! 🎉📣",
    "Good morning! Pretend you're already winning—soon it won't be pretend! 🏁💸",
    "Stretch, yawn, and go dominate! 🧘‍♂️💼",
    "Your potential just hit snooze. You didn’t. That’s power. 🛌⚡",
    "Every sunrise is proof you get another shot. 🎯🌄",
    "Break limits before breakfast. 🧱🥞",
    "Start your day like it's launch day! 🚀⏱️",
    "Mavericks don't snooze. They strategize. 🧠📊",
    "Good morning! Time to make the impossible nervous. 😳🔧",
    "You woke up. That means the universe just leveled up. 🌌🎮",
    "Mornings were invented for Mavericks to get ahead. 💨🏁",
    "Leave your bed like it's the last lap of a race! 🛏️🏁",
    "Sunlight or spotlight—Mavericks handle both. 🌞🎤",
    "Time to go from pajamas to power moves! 👕💼",
    "Say good morning to progress! ☀️📈",
    "Your mind is your best alarm clock. It just rang. 🧠⏰",
    "Get up like your dreams are waiting outside. 🏡💭",
    "Mornings aren't chill — they're challenge mode! 🕹️🔥",
    "That morning fog? It's fear leaving your body. 🌫️😤",
    "Nothing hits harder than a Maverick in the morning. 💥🌄",
    "Power walk into the day. Confidence level: Maverick. 🚶‍♀️💼",
    "If you're up, make it worth it. Let the grind begin. 🌀🔝",
    "Morning glory is earned, not given. 🏆🌅",
    "Start like you mean it. Finish like a legend. 🏁🦾"
  ],
afternoon: [
  "Good afternoon, Mavericks! Keep rocking that hustle! 🤘",
  "Hey Mavericks, time to refuel with some good vibes and snacks! 🍎😄",
  "Afternoon alert! Mavericks still winning, still grinning! 😁",
  "Keep calm and power through, Mavericks! Afternoon's your playground! 🎢",
  "Afternoon, Mavericks! Ready for a productivity power-up? ⚡",
  "Hey Mavericks, is it snack o'clock yet? Stay energized! 🍪🚀",
  "Afternoon sunshine to our unstoppable Mavericks! ☀️🔥",
  "Halfway through the day, Mavericks — still killing it! 💪",
  "Mavericks, let's turn this afternoon into a masterpiece! 🎨",
  "Good afternoon! Keep those brains buzzing, Mavericks! 🧠✨",
  "Mavericks in action: powering through the day like champs! 🏆",
  "Afternoon, Mavericks! The day's not over till you say so! 🕒",
  "Take a deep breath, Mavericks — and keep crushing goals! 🌬️💥",
  "Hey Mavericks, remember: naps are for quitters! Just kidding, take a quick one! 😴😉",
  "Afternoon Mavericks, your vibe attracts your tribe! Keep it lit! 🔥",
  "Hello Mavericks! Time for an afternoon pep talk: You've got this! 🙌",
  "Mavericks, coffee's good, but your passion's better! ☕❤️",
  "Afternoon roll call! Who's ready to smash some tasks? 📝🔥",
  "Keep your spirits high and your coffee higher, Mavericks! ☕🚀",
  "Mavericks, every afternoon is a fresh chance to shine brighter! ✨",
  "Afternoon vibes: Mavericks making waves and taking names! 🌊✍️",
  "Halfway through, Mavericks — let's make the rest of the day count! ⏳",
  "Hey Mavericks, your afternoon hustle is legendary! Keep it up! 🏅",
  "Afternoon champs, keep your eyes on the prize and your feet on the ground! 🎯",
  "Mavericks, you're the reason the afternoon rocks! 🎸😄",
  "Still standing? Still slaying! That's the Maverick way! 🔥💯",
  "Afternoon slump? Never heard of her! 💅☕",
  "Post-lunch Mavericks be like: Let’s do this. Again. But better. 🥗💪",
  "Sun high, spirits higher — Mavericks don’t slow down! ☀️📈",
  "Keep calm, sip chai, and destroy deadlines. 🫖🗂️",
  "It’s not ‘just afternoon’ — it’s showtime round 2! 🎬🔥",
  "Midday warriors reporting for success duty! 🫡🛡️",
  "Energy level: 90%. Focus level: 100%. Maverick level: ∞ 🚀",
  "Hey sun, you’re not the only one shining this afternoon. 🌞😎",
  "Afternoons are where legends earn their badges. 🎖️⏱️",
  "Halfway done? Nah. You’re just heating up! 🔥💨",
  "Clock's ticking. So are Mavericks. Tick-tick-BOOM! 💣🕒",
  "Brain: 'I’m tired.' Mavericks: 'Not today, buddy!' 🧠🚫",
  "Stretch, smile, and shoot your next shot! 🎯😊",
  "Stay smooth, stay sharp, stay Maverick! 🧊🔪",
  "Your second wind just got its own soundtrack! 🎧⚡",
  "Even the shadows salute your grind right now! 🌤️🫡",
  "Sip. Slay. Repeat. ☕⚔️",
  "Midday magic happens when Mavericks keep going! 🪄💼",
  "Plot twist: You’re not tired — you’re just about to level up! ⏫😄",
  "You’re halfway to the weekend and 100% fire! 🔥📆",
  "Get up. Get loud. Get Maverick. 🎤💥",
  "This isn’t the mid-day dip. It’s the Maverick flip! 🔄🚀",
  "Keep building! Your goals are waving at you from 4 PM! 🏗️🕓",
  "Productivity check: You’re still the GOAT. 🐐📊",
  "Own the clock, don't watch it. 🕰️💼",
  "Success likes afternoon people. Especially the Maverick kind. 💁‍♂️🎯",
  "Brainstorm? More like brainstorming thunder! 🌩️🧠",
  "Mavericks don’t survive the afternoon — they own it! 👑🌞",
  "Every second from now = another step toward greatness. 🕑📈",
  "Put that snack in one hand, and greatness in the other. 🍩📋",
  "Let the caffeine guide you to glory! ☕🏁",
  "Refill water, refresh mindset, and restart like a pro! 💧🔁",
  "Afternoon Maverick Mode: ON. 🟢💪",
  "Need motivation? Just look at how far you’ve come today! 📍✨",
  "Slouching? Straighten up — you’ve got a legacy to build. 🧍‍♂️🏗️",
  "Inbox zero? Nah. Impact 100. 📩💣",
  "Your effort right now is future-you’s flex. 💼💪",
  "Tick tock, unlock! Let the afternoon be your playground! 🕒🔓",
  "Pro tip: every big win hides in small afternoon efforts. 💎📆",
  "Remember, some people nap now. You make history. 🛌➡️📜",
  "Mavericks aren't sleepy — they’re strategic. 🧠⚔️",
  "Afternoon heat = productivity fuel. 🔥🌡️",
  "The sun is high. So are your standards. 📈🌞",
  "One decision this afternoon can shift your entire path. Choose power! 🧭🗺️",
  "Your afternoon momentum is what morning people envy. 🏃‍♀️💼",
  "Work like everyone’s watching. And admiring. 😎👀",
  "Keep your hustle spicy and your break sweet! 🌶️🍫",
  "Mavericks don’t crash at noon — they cruise to greatness! 🛳️🏆"
],
    evening: [
  "Good evening, Mavericks! Time to kick back and relax like royalty! 👑",
  "Evening Mavericks! Did you win the day? Either way, celebrate! 🎉",
  "Sunset salute to our amazing Mavericks! You crushed it! 🌇🔥",
  "Evening vibes! Time to recharge your superhero powers! 🦸‍♂️⚡",
  "Hey Mavericks, time to unwind and share your epic stories! 📖✨",
  "Mavericks, the stars are out — just like your brilliance! 🌟",
  "Good evening! Time for some well-earned Maverick chill time! 😎🍹",
  "Evening, Mavericks! Let's toast to a day well conquered! 🥂",
  "Mavericks, don't just count stars — be one! ✨",
  "Evening! Hope your day was as awesome as you are, Mavericks! 💫",
  "Sunset and Mavericks — the perfect combo! 🌅🔥",
  "Time to swap your hustle hat for a chill cap, Mavericks! 🧢😌",
  "Evening Mavericks, let your mind relax and your dreams get wild! 🌙💭",
  "Cheers to Mavericks who hustle by day and dream big by night! 🍻",
  "Mavericks, the day's done — now time to plot tomorrow's victory! 🗺️",
  "Good evening! Even Mavericks need to Netflix and chill sometimes! 📺😄",
  "Sun's down, Mavericks — time to let your awesomeness glow! 🌃✨",
  "Evening, team! May your relaxation be as fierce as your work ethic! 🔥",
  "Mavericks, you earned this evening's peace and quiet! Enjoy it! 🌌",
  "Good evening! Remember, even legends need rest! 🛌",
  "Mavericks, the night is young and so is your potential! Go dream big! 🌠",
  "Evening vibes loading… Mavericks, you're doing amazing! 💻🌆",
  "Hey team, may your night be drama-free and snack-full! 🍕🌙",
  "Sit back, breathe deep, and enjoy your Maverick-made sunset. 🌇🧘",
  "Evening anthem: relax, reflect, recharge. 🕯️🎶",
  "Done conquering? Now it's time to chill like champions! 🏆🛋️",
  "Mavericks never settle, even when the sun sets! 🌄💼",
  "Evening alert: your smile needs no filter! 😁📸",
  "Golden hour hits different for golden teams like you! ✨📷",
  "Wrap the day like a gift — with pride and gratitude! 🎁🌙",
  "It’s not over till the stars shine on your name! 🌟📝",
  "Greatness doesn’t sleep. But it sure does relax with grace. 😌🔥",
  "Evening breeze whispers: 'You did great today, Maverick.' 💨🌆",
  "Take this moment — you earned every chill second of it. 🧊⏳",
  "Let go of stress. You're holding success now. 💼💤",
  "Turn off the rush, turn on the calm. You’re safe, you’re proud. 🧠🕊️",
  "Evening mode: soft lights, calm vibes, Maverick mood! 🛋️💡",
  "Power down work mode, power up self-love! 🧡⚙️",
  "Mavericks never forget to celebrate the small wins too! 🏅🍩",
  "Night whispers, ‘You showed up, and that was enough.’ 🌌❤️",
  "Time to plan the next mountain, but tonight — just float. 🏔️🎈",
  "Trade your laptop for a pillow and your planner for a book. 💻📚",
  "You moved the needle today, now move to the cozy couch! 🛋️🎯",
  "Evening hugs from the universe to the Maverick you are. 🤗🌌",
  "Let your achievements echo into the stars. 🪩🔊",
  "When sun goes down, your soul rises in peace. 🌅💗",
  "You handled today like a boss. Now rest like a king. 👑🛏️",
  "Evening = elegance. Let your calm sparkle. ✨🧘",
  "Put your phone down (after this greeting!) and feel the stillness. 📵😌",
  "Peace out, stress! Mavericks choose calm now. 🕊️🧠",
  "Snooze buttons are for mornings. This time is pure YOU. 🕰️🧡"
],
night: [
  "Good night, Mavericks! Dream big, rest well! 🌙💤",
  "Mavericks, the stars are watching — make sure you're dreaming of greatness! ✨",
  "Sleep tight, Mavericks! Tomorrow's another chance to be awesome! 😴🔥",
  "Night, Mavericks! Don't let the bedbugs steal your creativity! 🛏️🐞",
  "Mavericks, recharge your brain — it's time to power up! ⚡💤",
  "Good night! May your dreams be as epic as your hustle! 🌌💫",
  "Rest easy, Mavericks! You've earned your place among the stars! 🌟",
  "Sleep like a Maverick — fierce and unbreakable! 🛌🦁",
  "Nighty night, Mavericks! See you at the top tomorrow! 🏔️",
  "Dream on, Mavericks! Tomorrow is your canvas! 🎨🌙",
  "Good night! Even Mavericks need their beauty sleep! 💅😴",
  "Mavericks, close your eyes and open your mind to amazing dreams! 🌠",
  "Sleep well, champions! The world awaits your next move! 🏆",
  "Mavericks, rest now so you can rule tomorrow! 👑",
  "Good night! Let your dreams do the heavy lifting tonight! 🌛💪",
  "Mavericks, the night is your friend — recharge and rise! 🌙✨",
  "Sleep tight! Remember, the best ideas come after a good rest! 💡😴",
  "Mavericks, drift into dreams and wake up ready to conquer! 🌌🚀",
  "Good night! Your dreams are the blueprint for tomorrow's success! 📐🌟",
  "Rest well, Mavericks! Tomorrow's adventures await! 🌄",
  "Night, Mavericks! May your sleep be deep and your dreams wild! 🌙🌪️",
  "Mavericks, even heroes need their downtime! Recharge those powers! 🦸‍♀️💤",
  "Sleep tight, sleep right — Mavericks' motto for greatness! 💤🔥",
  "No alarms, just ambitions resting. 🛏️💭",
  "Stars above, goals below. See you at sunrise! 🌌🌄",
  "Dream wild — wake wilder. 😴🔥",
  "You're off-duty now, Maverick. Recharge like a legend. 🔋👑",
  "Bedtime checklist: pajamas, gratitude, ambition for tomorrow. ✅",
  "Power nap? Nah, this is full-on greatness loading! ⏳💤",
  "Snore with swagger, dream with direction. 😎🛌",
  "Tonight, let your spirit breathe. You’ve done more than enough. 🌬️🌌",
  "Rest is not a pause, it’s preparation. 🛌📈",
  "Night is the quiet applause for a day well lived. 👏🌠",
  "Let the darkness hug your thoughts in comfort. 🖤🧠",
  "Tonight's goal: become well-rested royalty. 👑😴",
  "Hibernate like a hero, wake like a warrior! 🐻⚔️",
  "Dream high. Fly higher tomorrow. 🕊️🌙",
  "Log out of life, log into imagination. 💻💭",
  "Your best self is being cooked in dreamland. 👨‍🍳💤",
  "Sleep = secret Maverick strategy. Don’t skip it. 🧠🔐",
  "Even dreams are afraid of your potential. 😴💣",
  "Sleep tight, skywalker. The universe is proud. ✨🚀",
  "Your ambition never sleeps, but you must. 😌🛏️",
  "Stars say hi. Your pillow says hug me. 🌟🛌",
  "You conquered the day. Now conquer the blanket. 🥇🛏️",
  "Sleep is just success in silent mode. 🔇🌃",
  "Rest isn’t quitting. It’s rebirth. 🌱💤",
  "Dreams are team Mavericks' training grounds. 🌌💪",
  "And now, we rest. Because tomorrow’s story needs energy. 📖⚡",
  "Hey Mavericks, it's shutdown o'clock! Time to let your brain reboot. 🛌💡",
  "Good night, legends! Your dreams deserve a standing ovation. 👏🌠",
  "Mavericks, drift into dreams like a boss—alarm set, soul calm. 😴💼",
  "Sleep like a rockstar, wake up like a legend. 🎤🌙",
  "Let your pillow be your throne tonight, O brave Maverick! 👑🛏️",
  "Every Maverick needs sleep to upgrade to version 2.0! 🔋💤",
  "Tonight’s goal: zero thoughts, one cozy blanket, infinite dreams. 🧠❌🛌",
  "You’ve slayed the dragons. Time to rest your sword, warrior. 🐉🗡️",
  "Good night! Let your snores be louder than your stress. 😌💤",
  "The stars outside are jealous of how bright you were today. ✨😎",
  "Maverick’s rule #99: Sleep well, dream wilder, rise stronger. 🌙📜",
  "Good night, dream chaser! Time to build in sleep what you’ll conquer tomorrow. 💭🚀",
  "Logging off from reality… entering the dreamverse. 🌐😴",
  "Close your eyes and let your imagination go full Maverick. 🧠🌌",
  "The universe says: 'Well done, now rest your magic.' 🌌🧙‍♂️",
  "Sleep like it’s your superpower — because it is. 🦸‍♀️💤",
  "Wrap yourself in sleep like your favorite hoodie. Comfy vibes only. 🛌🧥",
  "Your bed is calling — and it knows your worth. 📞🛏️",
  "Count blessings, not sheep. 🌟🙌",
  "Dear Mavericks: Rest now. Tomorrow, we rise again! 🌄🛡️",
  "Good night! The hustle clock will wait — for now, it’s dream time. ⏰🌙",
  "Snuggle mode: Activated. Stress: Logged out. Peace: Downloading… 💻🛌",
  "The sky is your blanket, and the stars are your cheerleaders tonight. ⭐🛌",
  "Night is when your soul whispers, 'Thanks for showing up today.' 💖🌌",
  "No more scrolling. No more goals. Just you, sleep, and stillness. 📱❌🧘"
]

};


export default greetings;